### ISSUE TITLE
大佬你好，请问我装完如何使用。 后台没有任何新增菜单。

### ISSUE THREAD

**Issue by Bossjava** [asundust/dcat-auth-google-2fa#1]
RT~感谢

composer show dcat/laravel-admin | grep version
versions : * 2.2.3-beta

**Comment by asundust** [comment]
对的无任何新增菜单，在插件那边安装好启用就行。扩展直接控制原先的用户体系的用户列表。

**Comment by Bossjava** [comment]
> 对的无任何新增菜单，在插件那边安装好启用就行。扩展直接控制原先的用户体系的用户列表。

谢谢大佬回复。

启用了扩展，但是管理员列表和表单 都没有新增任何项。

![image](https://github.com/asundust/dcat-auth-google-2fa/assets/53845535/05b2aab2-f738-418f-96fc-bcf5c99ad2f4)

![image](https://github.com/asundust/dcat-auth-google-2fa/assets/53845535/f00e2b3f-ac21-4d5d-a524-ec609ed26ddd)

**Comment by asundust** [comment]
网址是这个“admin/auth/users”吗？

**Comment by Bossjava** [comment]
> 网址是这个“admin/auth/users”吗？


建了多应用，不是admin， 这个后台访问地址为了安全修改过了，后面是一样的，目录也还是app/admin

**Comment by asundust** [comment]
请问改的ENV是`ADMIN_ROUTE_PREFIX`吗？我这很正常啊。
<img width="889" alt="image" src="https://github.com/asundust/dcat-auth-google-2fa/assets/6573979/64317d04-fa33-48f8-8eb1-b3c51d6f185a">
<img width="265" alt="image" src="https://github.com/asundust/dcat-auth-google-2fa/assets/6573979/4b50ae24-911e-4779-a801-dbb72663d65f">
<img width="936" alt="image" src="https://github.com/asundust/dcat-auth-google-2fa/assets/6573979/ea5f0ba1-ee3b-44b1-8797-9f161f0dd925">
