### ISSUE TITLE
与Laravel Jetstream共存的问题：pragmarx/google2fa版本冲突

### ISSUE THREAD

**Issue by 0x7k** [asundust/dcat-auth-google-2fa#2]
作者您好，

当我尝试在使用 Laravel Jetstream 的项目中安装 `asundust/dcat-auth-google-2fa` 时，遇到了 `pragmarx/google2fa` 的版本冲突问题。具体表现为，`asundust/dcat-auth-google-2fa` 需要的 `pragmarx/google2fa` 版本为 `^3.0`，而 Laravel Jetstream 的依赖 `laravel/fortify` 需要的版本为 `^7.0` 或 `^8.0`。

错误信息如下：

PS C:\www> composer require asundust/dcat-auth-google-2fa
./composer.json has been updated
Running composer update asundust/dcat-auth-google-2fa
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires asundust/dcat-auth-google-2fa * -> satisfiable by asundust/dcat-auth-google-2fa[dev-main, 1.0.0, 1.0.1, 9999999-dev].
    - asundust/dcat-auth-google-2fa[dev-main, 1.0.0, ..., 1.0.1] require pragmarx/google2fa ^3.0 -> found pragmarx/google2fa[v3.0.0, v3.0.1, v3.0.2, v3.0.3] but the package is fixed to v8.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.       

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require asundust/dcat-auth-google-2fa:*" to figure out if any version is installable, or "composer require asundust/dcat-auth-google-2fa:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
PS C:\www> composer why pragmarx/google2fa                          
laravel/fortify v1.18.0 requires pragmarx/google2fa (^7.0|^8.0) 

请问有可能调整此插件以解决与 `laravel/fortify` 的版本冲突吗？或者，是否有其他推荐的解决方案？

祝好！

**Comment by asundust** [comment]
已更新

**Comment by CouchpotatoMiner** [comment]
我擦大佬你也太厉害了吧，我刚才提交，牛逼👍
